export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE';

export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';

export const SET_USER_ROLE = 'SET_USER_ROLE';
export const CLIENT_INFO_SUCCESS = 'CLIENT_INFO_SUCCESS';
export const CLIENT_INFO_FAILURE = 'CLIENT_INFO_FAILURE';
export const CLIENT_INFO_EMAIL_ERROR = 'CLIENT_INFO_EMAIL_ERROR';
export const USER_INFO_EMAIL_ERROR = 'USER_INFO_EMAIL_ERROR';

export const FETCH_CLIENT_INFO_SUCCESS = 'FETCH_CLIENT_INFO_SUCCESS';
export const FETCH_CLIENT_INFO_FAILURE = 'FETCH_CLIENT_INFO_FAILURE';
export const STORE_MATCHING_CLIENT = 'STORE_MATCHING_CLIENT'; 
export const CLIENT_INFO_DELETE_SUCCESS = 'CLIENT_INFO_DELETE_SUCCESS'
export const CLIENT_INFO_DELETE_FAILURE = 'CLIENT_INFO_DELETE_FAILURE'
export const CLIENT_INFO_UPDATE_SUCCESS = 'CLIENT_INFO_UPDATE_SUCCESS'
export const CLIENT_INFO_UPDATE_FAILURE = 'CLIENT_INFO_UPDATE_FAILURE'

//for company
export const COMPANY_CREATE_SUCCESS = 'COMPANY_CREATE_SUCCESS';
export const COMPANY_CREATE_FAILURE = 'COMPANY_CREATE_FAILURE';
export const FETCH_COMPANY_INFO_SUCCESS = 'FETCH_COMPANY_INFO_SUCCESS';
export const FETCH_COMPANY_INFO_FAILURE = 'FETCH_COMPANY_INFO_FAILURE';
export const COMPANY_UPDATE_SUCCESS = 'COMPANY_UPDATE_SUCCESS';
export const COMPANY_UPDATE_FAILURE = 'COMPANY_UPDATE_FAILURE';
export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS';
export const COMPANY_DELETE_FAILURE = 'COMPANY_DELETE_FAILURE';

//FOR ROLE
export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS';
export const ROLE_DELETE_FAILURE = 'ROLE_DELETE_FAILURE';
export const ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS';
export const ROLE_UPDATE_FAILURE = 'ROLE_UPDATE_FAILURE';

export const LOGOUT = 'LOGOUT';

export const GET_ALL_DEPARTMENTS_SUCCESS = 'GET_ALL_DEPARTMENTS_SUCCESS';
export const GET_ALL_DEPARTMENTS_FAILURE = 'GET_ALL_DEPARTMENTS_FAILURE';

//district
export const GET_ALL_DISTRICT_SUCCESS = 'GET_ALL_DISTRICT_SUCCESS';
export const GET_ALL_DISTRICT_FAILURE = 'GET_ALL_DISTRICT_FAILURE';

//designation
export const GET_ALL_DESIGNATION_SUCCESS = 'GET_ALL_DESIGNATION_SUCCESS';
export const GET_ALL_DESIGNATION_FAILURE = 'GET_ALL_DESIGNATION_FAILURE';

//edit
export const GET_ALL_EMPLOYEE = 'GET_ALL_EMPLOYEE';